package Vista;
// aprobado

import Clases.Casillas;
import Conexiones.Usuario;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSlider;

public class Configuraciones extends javax.swing.JFrame {

    //modoJuego: almacena 1 si el modo de juego es de un jugador, 2 si es de dos jugadores
    private int modoJuego;
    //primera: almacena true en caso de que sea el primer tablero, y false en caso de ser el segundo
    private boolean primera = true;
    Graphics graphics;
    Color selectedColorP1 = Color.white, selectedColorP2 = Color.white;

    /**
     * Creates new form Configuraciones
     */
    public Configuraciones(int modoJuego) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.modoJuego = modoJuego;
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/Serpiente.jpg")).getImage());

        // rellenar los comboBox
        Usuario usuarios = new Usuario();
        ArrayList<String> user = usuarios.obtenerUsuarios();

        //En caso de ser el modo de dos jugadores
        if (modoJuego == 1) {
            //Se quitan la label y combo box que pertenecen al segundo jugador
            P2Label.setVisible(false);
            cmbP2.setVisible(false);
            btnAgregar.setVisible(true);
            slBlueP2.setVisible(false);
            slRedP2.setVisible(false);
            slGreenP2.setVisible(false);
            lblJugador2.setVisible(false);
            pnColorP2.setVisible(false);

            // ciclo para rellenar datos, pero solo del primer jugador
            for (int i = 0; i < user.size(); i++) {
                cmbP1.addItem(user.get(i));
            }

        } else {
            // ciclo para rellenar datos de ambos jugadores
            for (int i = 0; i < user.size(); i++) {
                cmbP1.addItem(user.get(i));
                cmbP2.addItem(user.get(i));
            }
        }

        setLocationRelativeTo(null);

        jPanel2.setBackground(new Color(60, 63, 65, 225));

        graphics = pnColorP1.getGraphics();
        pnColorP1.paintComponents(graphics);

        //Se manda la imagen del tablero para que se adapte al tamaño del label
        EscalaImagen(ImagenSeleccionada());
    }

    //Permite que la imagen sea adaptada al tamaño buscado
    public void EscalaImagen(String url) {
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
        Image img = imgIcon.getImage();
        Image imgScale = img.getScaledInstance(tableroLabel.getWidth(), tableroLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);

        //Coloca la imagen en el label correspondiente
        tableroLabel.setIcon(scaledIcon);
    }

    //Devuelve la imagen seleccionada
    public String ImagenSeleccionada() {
        String url = "";

        //En caso de que el jugador haya seleccionado el primer tablero devuelve la direccion respectiva de la imagen
        if (primera) {
            return "/imagenes/Tablero1.jpg";

            //En caso de haber seleccionado la imagen del segundo tablero
        } else {
            return "/imagenes/Tablero2.jpg";
        }
    }

    //Cambia el valor de primera en base a las flechas presionadas para cambiar de tablero
    public void CambioBool() {
        if (primera) {
            primera = false;
        } else {
            primera = true;
        }
    }

    //Permite la configuración de las casillas en base al tablero seleccionado
    private Casillas ConfigCasillas() {
        if (primera) {
            return new Casillas(75, 355, 140, 77, 30, 6, primera);

        } else {
            return new Casillas(71, 363, 117, 55, 49, 7, primera);
        }
    }

    private Color GetColor(JSlider r, JSlider g, JSlider b, JPanel panel) {
        Color newColor = new Color(r.getValue(), g.getValue(), b.getValue());

        panel.setBackground(newColor);

        return newColor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        avisoFicha = new javax.swing.JLabel();
        slcTableroLbl = new javax.swing.JLabel();
        btnIzqTablero = new javax.swing.JButton();
        btnSve = new javax.swing.JButton();
        tableroLabel = new javax.swing.JLabel();
        btnDerTablero = new javax.swing.JButton();
        lblJugador2 = new javax.swing.JLabel();
        P1Label = new javax.swing.JLabel();
        P2Label = new javax.swing.JLabel();
        pnColorP1 = new javax.swing.JPanel();
        cmbP1 = new javax.swing.JComboBox<>();
        cmbP2 = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        slRedP1 = new javax.swing.JSlider();
        slGreenP1 = new javax.swing.JSlider();
        slBlueP1 = new javax.swing.JSlider();
        slRedP2 = new javax.swing.JSlider();
        pnColorP2 = new javax.swing.JPanel();
        slGreenP2 = new javax.swing.JSlider();
        slBlueP2 = new javax.swing.JSlider();
        slcFichaLbl1 = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avisoFicha.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        avisoFicha.setForeground(new java.awt.Color(255, 255, 255));
        avisoFicha.setText("Selecciona tu jugador");
        avisoFicha.setAlignmentX(320.0F);
        avisoFicha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(avisoFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        slcTableroLbl.setFont(new java.awt.Font("Lucida Console", 1, 16)); // NOI18N
        slcTableroLbl.setForeground(new java.awt.Color(255, 255, 255));
        slcTableroLbl.setText("Elige el tablero");
        slcTableroLbl.setAlignmentX(320.0F);
        slcTableroLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(slcTableroLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 155, -1, -1));

        btnIzqTablero.setBackground(new java.awt.Color(0, 0, 0));
        btnIzqTablero.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        btnIzqTablero.setForeground(new java.awt.Color(255, 255, 255));
        btnIzqTablero.setText("<");
        btnIzqTablero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIzqTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzqTableroActionPerformed(evt);
            }
        });
        jPanel2.add(btnIzqTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, 45, 40));

        btnSve.setBackground(new java.awt.Color(0, 0, 0));
        btnSve.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnSve.setForeground(new java.awt.Color(255, 255, 255));
        btnSve.setText("Guardar");
        btnSve.setAlignmentX(320.0F);
        btnSve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSve, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 116, 31));
        jPanel2.add(tableroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 184, 167, 91));

        btnDerTablero.setBackground(new java.awt.Color(0, 0, 0));
        btnDerTablero.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        btnDerTablero.setForeground(new java.awt.Color(255, 255, 255));
        btnDerTablero.setText(">");
        btnDerTablero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDerTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerTableroActionPerformed(evt);
            }
        });
        jPanel2.add(btnDerTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 214, 45, 40));

        lblJugador2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblJugador2.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador2.setText("P2");
        lblJugador2.setAlignmentX(320.0F);
        lblJugador2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        P1Label.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        P1Label.setForeground(new java.awt.Color(255, 255, 255));
        P1Label.setText("P1");
        P1Label.setAlignmentX(320.0F);
        P1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(P1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        P2Label.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        P2Label.setForeground(new java.awt.Color(255, 255, 255));
        P2Label.setText("P2");
        P2Label.setAlignmentX(320.0F);
        P2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(P2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        javax.swing.GroupLayout pnColorP1Layout = new javax.swing.GroupLayout(pnColorP1);
        pnColorP1.setLayout(pnColorP1Layout);
        pnColorP1Layout.setHorizontalGroup(
            pnColorP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        pnColorP1Layout.setVerticalGroup(
            pnColorP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(pnColorP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 72));

        jPanel2.add(cmbP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 110, -1));

        jPanel2.add(cmbP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 110, -1));

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar Usuario");
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 126, 40));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 126, 40));

        slRedP1.setMaximum(255);
        slRedP1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slRedP1StateChanged(evt);
            }
        });
        jPanel2.add(slRedP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 99, -1));

        slGreenP1.setMaximum(255);
        slGreenP1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slGreenP1StateChanged(evt);
            }
        });
        jPanel2.add(slGreenP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 99, -1));

        slBlueP1.setMaximum(255);
        slBlueP1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slBlueP1StateChanged(evt);
            }
        });
        jPanel2.add(slBlueP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 99, -1));

        slRedP2.setMaximum(255);
        slRedP2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slRedP2StateChanged(evt);
            }
        });
        jPanel2.add(slRedP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 99, -1));

        javax.swing.GroupLayout pnColorP2Layout = new javax.swing.GroupLayout(pnColorP2);
        pnColorP2.setLayout(pnColorP2Layout);
        pnColorP2Layout.setHorizontalGroup(
            pnColorP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        pnColorP2Layout.setVerticalGroup(
            pnColorP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(pnColorP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 71, -1, 72));

        slGreenP2.setMaximum(255);
        slGreenP2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slGreenP2StateChanged(evt);
            }
        });
        jPanel2.add(slGreenP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 99, -1));

        slBlueP2.setMaximum(255);
        slBlueP2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slBlueP2StateChanged(evt);
            }
        });
        jPanel2.add(slBlueP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 99, -1));

        slcFichaLbl1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        slcFichaLbl1.setForeground(new java.awt.Color(255, 255, 255));
        slcFichaLbl1.setText("Color de la ficha");
        slcFichaLbl1.setAlignmentX(320.0F);
        slcFichaLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(slcFichaLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblJugador1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblJugador1.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador1.setText("P1");
        lblJugador1.setAlignmentX(320.0F);
        lblJugador1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnMenu.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Regresar");
        btnMenu.setAlignmentX(320.0F);
        btnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 116, 31));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 600, 380));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzqTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzqTableroActionPerformed
        //Cambia el valor de primera
        CambioBool();

        //Escala la imagen seleccionada
        EscalaImagen(ImagenSeleccionada());
    }//GEN-LAST:event_btnIzqTableroActionPerformed

    private void btnSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSveActionPerformed
        //Verifica el modo de juego seleccionado
        switch (modoJuego) {
            //En caso de ser un jugador
            case 1: {
                //Manda a llamar la ventana de un jugador enviandole todos los datos necesarios y cierra esta (Configuraciones)
                UnJugador unJugador = new UnJugador(ImagenSeleccionada(), ConfigCasillas(),
                        String.valueOf(cmbP1.getSelectedItem()), selectedColorP1, primera);
                unJugador.setVisible(true);

                this.dispose();

                break;
            }

            //En caso de ser dos jugadores
            case 2:
                //Verifica si los nombres de usuario son iguales
                if (cmbP1.getSelectedItem().equals(cmbP2.getSelectedItem())) {

                    //En caso de ser iguales muestra una advertencia y no permite el guardado
                    JOptionPane.showMessageDialog(null, "No puede elegir el mismo nickname dos veces",
                            "Error", JOptionPane.ERROR_MESSAGE);
                } else if (selectedColorP1.getRGB() == selectedColorP2.getRGB()) {
                    JOptionPane.showMessageDialog(null, "No puede elegir el mismo color dos veces",
                            "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    DosJugadores dosJugadores = new DosJugadores(ImagenSeleccionada(), ConfigCasillas(),
                            ConfigCasillas(), String.valueOf(cmbP1.getSelectedItem()),
                            String.valueOf(cmbP2.getSelectedItem()), selectedColorP1, selectedColorP2, primera);
                    dosJugadores.setVisible(true);

                    this.dispose();
                }

                break;
        }
    }//GEN-LAST:event_btnSveActionPerformed

    private void btnDerTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerTableroActionPerformed
        //Cambia el valor de primera
        CambioBool();

        //Escala la imagen seleccionada
        EscalaImagen(ImagenSeleccionada());
    }//GEN-LAST:event_btnDerTableroActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        AgregarUsuario NewForm = new AgregarUsuario();
        NewForm.setVisible(true);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // prueba 
        // rellenar los comboBox
        Usuario usuarios = new Usuario();
        ArrayList<String> user = usuarios.obtenerUsuarios();

        //En caso de ser el modo de dos jugadores
        if (modoJuego == 1) {
            //Se quitan la label y combo box que pertenecen al segundo jugador
            P2Label.setVisible(false);
            cmbP2.setVisible(false);
            btnAgregar.setVisible(true);

            // ciclo para rellenar datos, pero solo del primer jugador
            for (int i = 0; i < user.size(); i++) {
                cmbP1.addItem(user.get(i));
            }

        } else {
            // ciclo para rellenar datos de ambos jugadores
            for (int i = 0; i < user.size(); i++) {
                cmbP1.addItem(user.get(i));
                cmbP2.addItem(user.get(i));
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void slRedP1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slRedP1StateChanged
        // TODO add your handling code here:
        selectedColorP1 = GetColor(slRedP1, slGreenP1, slBlueP1, pnColorP1);
    }//GEN-LAST:event_slRedP1StateChanged

    private void slGreenP1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slGreenP1StateChanged
        selectedColorP1 = GetColor(slRedP1, slGreenP1, slBlueP1, pnColorP1);
    }//GEN-LAST:event_slGreenP1StateChanged

    private void slBlueP1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slBlueP1StateChanged
        selectedColorP1 = GetColor(slRedP1, slGreenP1, slBlueP1, pnColorP1);
    }//GEN-LAST:event_slBlueP1StateChanged

    private void slRedP2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slRedP2StateChanged
        selectedColorP2 = GetColor(slRedP2, slGreenP2, slBlueP2, pnColorP2);
    }//GEN-LAST:event_slRedP2StateChanged

    private void slGreenP2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slGreenP2StateChanged
        selectedColorP2 = GetColor(slRedP2, slGreenP2, slBlueP2, pnColorP2);
    }//GEN-LAST:event_slGreenP2StateChanged

    private void slBlueP2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slBlueP2StateChanged
        selectedColorP2 = GetColor(slRedP2, slGreenP2, slBlueP2, pnColorP2);
    }//GEN-LAST:event_slBlueP2StateChanged

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu menu = new Menu();

        menu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuraciones(2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P1Label;
    private javax.swing.JLabel P2Label;
    private javax.swing.JLabel avisoFicha;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDerTablero;
    private javax.swing.JButton btnIzqTablero;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSve;
    private javax.swing.JComboBox<String> cmbP1;
    private javax.swing.JComboBox<String> cmbP2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JPanel pnColorP1;
    private javax.swing.JPanel pnColorP2;
    private javax.swing.JSlider slBlueP1;
    private javax.swing.JSlider slBlueP2;
    private javax.swing.JSlider slGreenP1;
    private javax.swing.JSlider slGreenP2;
    private javax.swing.JSlider slRedP1;
    private javax.swing.JSlider slRedP2;
    private javax.swing.JLabel slcFichaLbl1;
    private javax.swing.JLabel slcTableroLbl;
    private javax.swing.JLabel tableroLabel;
    // End of variables declaration//GEN-END:variables
}
